version: 2

models:
  - name: fact_trips
    columns:
      - name: trip_sk
        tests:
          - is_valid_sk 

  - name: dim_customers
    columns:
      - name: customer_sk
        tests:
          - is_valid_sk

  - name: dim_drivers
    columns:
        - name: driver_sk
          tests:
            - is_valid_sk
  - name: fact_payments
    columns:
        - name: payment_sk
          tests:
            - is_valid_sk

  - name: dim_vehicles
    columns:
       - name: vehicle_sk
         tests:
            - is_valid_sk

  - name: dim_date
    columns:
       - name: date_sk
         tests:
            - is_valid_sk